require:
  - rubocop-rails
  - rubocop-rspec

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
  EnforcedStyle: always

Rails/FilePath:
  Enabled: false

Metrics/MethodLength:
  Exclude:
    - 'db/migrate/*'
